extract_alerts_args:
  index_cache_dir: "file:///tmp/index_cache_dir/"
  tile_store_dir: "file:///dfive-default/rslearn-eai/datasets/forest_loss_driver/tile_store_root_dir/"
  workers: 112
  countries: ["PE", "BR", "CO"]
  gcs_tiff_filenames:
    - "040W_10S_030W_00N.tif"
    - "040W_20S_030W_10S.tif"
    - "050W_00N_040W_10N.tif"
    - "050W_10S_040W_00N.tif"
    - "050W_20S_040W_10S.tif"
    - "060W_00N_050W_10N.tif"
    - "060W_10S_050W_00N.tif"
    - "060W_20S_050W_10S.tif"
    - "070W_00N_060W_10N.tif"
    - "070W_10S_060W_00N.tif"
    - "070W_20S_060W_10S.tif"
    - "080W_00N_070W_10N.tif"
    - "080W_10S_070W_00N.tif"
    - "080W_20S_070W_10S.tif"
select_least_cloudy_images_args:
  workers: 112
